
name: Deploy GitHub Pages

# 触发条件：在 push 到 master 分支后
on:
   push:
      branches: [ main ]
  
  workflow_dispatch:

# 任务
jobs:
   build-and-deploy:
      # 服务器环境：最新版 Ubuntu
      runs-on: ubuntu-latest
      steps:
         # 拉取代码
         - name: Checkout
           uses: actions/checkout@v2
           with:
              persist-credentials: false

         # 生成静态文件（export NODE_OPTIONS=--max_old_space_size=4096  解决JavaScript heap out of memory问题）
         - name: Build
           run: yarn  && export NODE_OPTIONS=--max_old_space_size=4096 && yarn run build

         # 部署到 GitHub Pages
         - name: Deploy
           uses: JamesIves/github-pages-deploy-action@releases/v3
           with:
              ACCESS_TOKEN: ${{ secrets.JAVA_TOKEN }}
              BRANCH: gh-pages
              FOLDER: .vuepress/dist # 静态资源目录
